[package]
name = "moonshine-behavior"
version = "0.1.1"
edition = "2021"
license = "MIT"
description = "Minimalistic state machine for Bevy game engine."
homepage = "https://github.com/Zeenobit/moonshine_behavior"
repository = "https://github.com/Zeenobit/moonshine_behavior"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy_app = "0.12.*"
bevy_ecs = "0.12.*"
bevy_reflect = "0.12.*"
bevy_utils = "0.12.*"

[dev-dependencies]
bevy = "0.12.*"
